app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__, template_folder='templates', static_folder='statics')

from . import views
from ..models import *

app/main/views.py
from flask import render_template, redirect,\
    url_for, abort, flash, current_app,\
    request, make_response
    
from . import main
from .. import db
from ..models import Book, Price, MainProduct, AssociateBook
from time import strftime
from rq.command import send_stop_job_command
from sqlalchemy import desc
import datetime


@main.route('/')
def index():
    books = MainProduct.query.order_by(desc(MainProduct.updated_on)).limit(10)
    return render_template('index.html', title="صفحه اصلی", books=books)

@main.route('/book/<id>', methods=['GET'])
def ShowBook(id=None):    
    id = id
    book = db.session.query(MainProduct).filter(MainProduct.slug == id).first_or_404(description='There is no data with this {} information.'.format(id))
    relateds = db.session.query(Book, AssociateBook).join(AssociateBook, (Book.book_id == AssociateBook.book_id)&(AssociateBook.product_id == book.id)).all()
    # TODO: fack data, remove later
    labels = [
        'JAN', 'FEB', 'MAR', 'APR',
        'MAY', 'JUN', 'JUL', 'AUG',
        'SEP', 'OCT', 'NOV', 'DEC']
    values = [
        967.67, 1190.89, 1079.75, 1349.19,
        2328.91, 2504.28, 2873.83, 4764.87]
    return render_template('product.html', title=book.name, book=book, relateds=relateds, labels=labels, values=values, max=20000)


# handle 404 errors
@main.errorhandler(404)
def not_found(error):
    return render_template('error.html', title="404, Page not found"), 404

@main.route('/subproduct/<id>', methods=['GET'])
def ShowSubProduct(id):
    subproduct = db.session.query(Book).filter(Book.book_id == id).first_or_404()
    return render_template('subproduct.html', title=subproduct.name , product=subproduct)


    
    

app/main/templates/book.html
{% extends "layout.html" %}
{% set active_page = "books" %}
{% block head %}
  {{ super() }}
{% endblock %}
{% block content %}
        <div class="container">
            <div class="row clearfix">
                    {% for book in data %}
                    <div class="col-md-3 col-sm-6 col-xs-12">
                        <div class="card m-2" style="height: 40rem;">
                            <img src={{book.img}} class="card-img-top" alt={{book.name}} height="300px" width="auto">
                            <div class="card-header text-center" style="height: 20rem;">
                              <h5 class="card-title mb-4">{{book.name}}</h5>
                            </div>
                            <div class="card-body text-center">
                                <ul class="list-group list-group-flush text-center">
                                    <li class="list-group-item">
                                      {% if book.special_price != 0 %}
                                      <p><span class="text-success fs-3">{{book.special_price}} </span></p>
                                      <p><span class="text-danger fs-5 text-decoration-line-through">{{book.current_price}} </span></p>
                                      {% else %}
                                      <span class="fs-5">{{book.current_price}}</span>
                                      {% endif %}
                                    </li>
                                  </ul>
                            </div>
                            <div class="card-footer">
                                <div class="row align-items-end">
                                    <div class="col d-grid gap-1">
                                       <a href={{url_for("main.ShowBook",id=book.book_id)}} class="text-decoration-none text-dark btn btn-success">ادامه مطلب</a>
                                    </div>   
                                </div>
                            </div>
                          </div>
                    </div>
                    {% endfor%}
                </div>
            </div>
{% endblock %}
    <script>
     $(document).ready(function(){
         $("#livebox").on("input",function(e){
             $("#datalist").empty();
             $("#spinner").removeClass("hide");
             $("#intro").addClass("hide")
             if($("#livebox").val() != '')
             {
                 $.ajax({
                     method:"post",
                     url:"/livesearch",
                     data:{text:$("#livebox").val()},
                     success:function(res){
                         if(res != '')
                         {
                             var data = ""
                             $.each(res, function(index,value){
                                 data += "<div class=\"col-md-3 mb-2 mt-2 \"><div style='width:255;height:600;' class=\"card shadow-sm rounded \"><img style=\"width:auto; height:333;\" class=\"card-img-top\" src="+value['img']+" alt=\"Card image cap\">";
                                 data += "<div class=\"card-body\">"
                                 data += "<h5 class=\"card-title\">"+value['name']+"</h5>";
                                 if(value['specialprice'] != 0)
                                 {
                                     data += "<p class=\"card-text\"> <del>"+value['price']+"</del></p>";
                                     data += "<b class=\"card-text text-danger\"> "+value['specialprice']+" </b>";
                                 }
                                 else
                                 {
                                     data += "<p class=\"card-text\">"+value['price']+"</p>";
                                 }
                                 data += "</div> <div class=\"card-footer text-muted\"><a href=/product/"+value['id']+" class=\"btn btn-block btn-primary\">جزئیات</a></div></div></div>"
                             });
                             $("#datalist").html(data);
                         }
                         else
                         {
                             var data = "<h1>محصولی با این جزئیات یافت نشد.</h1>"
                             $("#datalist").html(data);
                         }
                     },
                     complete: function () { //adding the .hidden class to remove spinner at then end of response.
                         $('#spinner').addClass('hide')
                     },
                 });
             }
             else
             {
                 $("#datalist").html('');
                 $('#spinner').addClass('hide');
                 $('#db').addClass('hide');
                 $("#intro").removeClass("hide")
             }
         });
     });
    </script>

app/main/templates/error.html
<html>
    <body>
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
        <div class="page-404">
            <div class="outer">
                <div class="middle">
                    <div class="inner">
                        <!--BEGIN CONTENT-->
                        <div class="inner-circle"><i class="fa fa-home"></i><span>404</span></div>
                        <span class="inner-status">چنین صفحه‌ای وجود ندارد</span>
                            <a href={{url_for('index')}} class="btn btn-danger ">
                                صفحه اصلی
                            </a> 
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

app/main/templates/index.html
{% extends "layout.html" %}
{% set active_page = "index" %}
{% block head %}
{{ super() }}

{% endblock %}
{% block content %}
<div class="container">
    <div class="row clearfix" id="datalist">
        
    </div>
    <div class="row clearfix" id="origin">
        {% for book in books %}
        <div class="col-md-4">
            <div class="card shadow-lg rounded ">
                <img style="width:auto; height:333;" class="card-img-top" src="{{book.img}}" alt="Card image cap">
                <div class="card-body" style="height: 150px;">
                    <h5 class="card-title">{{book.name}}</h5>
                </div> 
                <div class="card-footer text-muted text-center"><a href="{{url_for('.ShowBook', id=book.slug)}}" class="btn btn-block btn-primary">جزئیات</a>
                </div>
            </div>
            </div>
        <!-- <div class="col-md-4 col-sm-6 col-xs-12">
            <div class="card m-2 shadow-lg rounded" style="height: 40rem;">
                <a href="{{url_for('main.ShowBook',id=book.slug)}}"><img src={{book.img}} class="card-img-top" alt={{book.name}} height="300px" width="auto"></a>
                <div class="card-header text-center" style="height: 20rem;">
                </div>
                <div class="card-body text-center">
                    <ul class="list-group list-group-flush text-center">
                        <li class="list-group-item">
                            {{book.name}}
                        </li>
                    </ul>
                </div>
                <div class="card-footer">
                    <div class="row ">
                        <span class="text-center text-secondary">
                            last update:
                            {{book.updated_on}}
                        </span>
                    </div>
                </div>
            </div>
        </div> -->
        {% endfor %}
    </div>
</div>
<script>
    $(document).ready(function(){
        $("#livebox").on("input",function(e){
            if($("#livebox").val().length >= 4)
            {
                $("#datalist").empty();
                $('#origin').hide()
                $("#spinner").removeClass("hide");
                $("#intro").addClass("hide")
                $.ajax({
                    method:"PUT",
                    url:"{{url_for('api.livesearch')}}",
                    data:{text:$("#livebox").val()},
                    success:function(res){
                        console.log(res)
                        if(res != '')
                        {
                            console.log(res)
                            var data = ""
                            $.each(res, function(index,value){
                                data += "<div class=\"col-md-4\"><div class=\"card shadow-sm rounded \"><img style=\"width:auto; height:333;\" class=\"card-img-top\" src="+value['img']+" alt=\"Card image cap\">";
                                data += "<div  style='height:150px;' class=\"card-body\">"
                                data += "<h5 class=\"card-title\">"+value['name']+"</h5>";
                            
                                data += "</div> <div class=\"card-footer text-muted text-center\"><a href=/book/"+value['slug']+" class=\"btn btn-block btn-primary\">جزئیات</a></div></div></div>"
                            });
                            $("#datalist").html(data);
                        }
                        else
                        {
                            var data = "<h1>محصولی با این جزئیات یافت نشد.</h1>"
                            $("#datalist").html(data);
                        }
                    },
                    complete: function () { // Set our complete callback, adding the .hidden class and hiding the spinner.
                        $('#spinner').addClass('hide')
                        
                    },
                });
            }
            else
            {
                $("#datalist").html('');
                $('#spinner').addClass('hide');
                $('#db').addClass('hide');
                $("#intro").removeClass("hide");
                
            }
            if($("#livebox").val() === '' | $("#livebox").val().length < 4 ){
                $('#origin').show();
            }
        });
    });
</script>
{% endblock %}

app/main/templates/layout.html
<!doctype html>
<html dir="rtl" lang="fa">
  <head>
    {% block head %}
    <title>{{ title }} | رقبا</title>
    <link rel="stylesheet" href={{url_for('static', filename='bootstrap.rtl.min.css')}} >    
    <script src={{url_for('static', filename='bootstrap.bundle.min.js')}}></script>
    <link rel="stylesheet" href={{url_for('static', filename='style.css') }}>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <style  type="text/css" media="screen">
  
     * {
         font-family: Vazir;
     }
     .hide{
         display:none;
     }
     nav li {
         margin-left: 30px;
         margin-right: 30px;
     }
     footer {
        position:static;
        bottom: 0;
        width: 100%;
    }
    </style>
    {% endblock %}
  </head>
  <body class="bg-light">
    <div id="container">
        <nav class="navbar sticky-top navbar-dark bg-dark navbar-expand-lg mb-5">
            <div class="container-fluid">
                <form class="d-flex">
                    <input type="text" id="livebox" class="form-control text-right" placeholder="نام کالا را وارد کنید" aria-label="Username" aria-describedby="addon-wrapping">
                  </form><button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                  <ul class="navbar-nav">
                    <li class="nav-item">
                      <a {% if active_page == "index" %} class="nav-link active" {% else %} class="nav-link" {% endif %} aria-current="index" href="/">صفحه اصلی</a>
                    </li>
                    <li class="nav-item">
                      </li>
                      <!-- <li class="nav-item">
                        <a {% if active_page == "newBooks" %} class="nav-link active" {% else %} class="nav-link" {% endif %} href={{url_for('.newBooks')}}>New Books</a>
                      </li> -->
                      <li class="nav-item">
                        <a {% if active_page == "dashboard" %} class="nav-link active" {% else %} class="nav-link" {% endif %} href={{url_for('dashboard.showProduct')}}>داشبورد</a>
                      </li>
                    <li class="nav-item">
                        <a class="btn btn-outline-danger" href="/rq">مشاهده وضعیت کرال <i class="fas fa-database"></i></a>
                        </li><li class="nav-item">
                          <a href="{{url_for('api.runCrawler')}}" class="btn btn-outline-primary">به روز رسانی اطلاعات</a>
                        </li>
                  </ul>
                </div>
                
              </div>
          </nav>
        {% block content %}{% endblock %}
    </div>
      {% block footer %}
      <footer class="">
        <div class="container-fluid bg-white">         
            <div class="row justify-content-center pt-3">
              <div class="col">
                  <small><a class="text-success text-decoration-none" href="https://codeberg.org/Safariyan"><p class="text-right">طراح: مهدی صفریان</p></a></small>
                </div>
                <div class="col-7">
                  <small><a class="text-success text-decoration-none" href="https://codeberg.org/Safariyan/dummyCrawler/src/branch/master/LICENSE"><p class="text-right">Copyright (C) 2021 M.Safarian | GPL-3</p></a></small>
                </div>
              </div>
          </div>
      </footer>
      {% endblock %}
  </body>
</html>

app/main/templates/newBooks.html
{% extends "layout.html" %}
{% block head %}
  {{ super() }}
{% endblock %}
{% block content %}
<div class="container">
    <div class="row clearfix">
            {% for book in books %}
            <div class="col-md-3 col-sm-6 col-xs-12">
                <div class="card m-2" style="height: 40rem;">
                    <img src={{book.img}} class="card-img-top" alt={{book.name}} height="300px" width="auto">
                    <div class="card-header text-center" style="height: 20rem;">
                      <h5 class="card-title mb-4">{{book.name}}</h5>
                    </div>
                    <div class="card-body text-center">
                        <ul class="list-group list-group-flush text-center">
                            <li class="list-group-item">
                              {% if book.special_price != 0 %}
                              <p><span class="text-success fs-3">{{book.special_price}} </span></p>
                              <p><span class="text-danger fs-5 text-decoration-line-through">{{book.current_price}} </span></p>
                              {% else %}
                              <span class="fs-3">{{book.current_price}}</span>
                              {% endif %}
                            </li>
                          </ul>
                    </div>
                    <div class="card-footer">
                        <div class="row align-items-end">
                            <div class="col d-grid gap-1">
                                <button class="btn btn-success" type="button"><a href={{url_for("main.ShowBook",id=book.book_id)}} class="text-decoration-none text-dark">ادامه مطلب</a></button>
                            </div>   
                        </div>
                    </div>
                  </div>
            </div>
            {% endfor%}
        </div>
{% endblock %}

app/main/templates/product.html
{% extends "layout.html"%}
{% set active_page = "products" %}
{% block head %}
<script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js'></script>

{{ super() }}

{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="shadow-lg p-2 bg-body rounded text-center">
        <img src="{{book.img}}" alt="" class="img-responsive push-bit rounded" height="200px">
      </div>
    </div>
    <div class="col-md-8 align-middle">
      <div class="shadow-lg p-5 bg-body rounded">
        <div class="bg-light rounded-pill p-3 mb-3">
          <p class="h1 text-right">{{book.name}}</p>
        </div>
        {%if book.special_price !=0%}
        <div class="p-3">
          <label for="specialPrice">قیمت ویژه:</label>
          <p><span class="h2 fs-2 fw-bold text-danger" id="specialPrice">{{book.special_price}}</span></p>
          <label for="currentPrice">قیمت اصلی:</label>
          <p><span class="h2 text-decoration-line-through fs-4" id="currentPrice">{{book.current_price}}</span></p>
        </div>
        {%else%}
        <div class="p-3">
          <label for="currentPrice">قیمت اصلی:</label>
          <span class="h2 " id="currentPrice">{{book.current_price}}</span>
        </div>
        {%endif%}
      </div>
    </div>
  </div>
</div>
<hr>
<div class="container">
  <div class="row">
    <h2>محصولات مرتبط</h2>
    <div class="col-md-8 offset-2">
      <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
        {% for book,related in relateds %}
        <li class="nav-item" role="presentation">
          <img src="{{ url_for('main.static', filename=(related.book_id.split('-')[0]+'.png')) }}"
            alt="{{related.book_id.split('-')[0]}}" class="" id="pills-{{related.book_id.split('-')[0]}}-tab"
            data-bs-toggle="pill" data-bs-target="#pills-{{related.book_id.split('-')[0]}}" type="button" role="tab"
            aria-controls="pills-{{related.book_id.split('-')[0]}}" aria-selected="true" width="100px" height="">
        </li>
        {% endfor %}
      </ul>
      <div class="tab-content" id="pills-tabContent">
        {% for book,related in relateds %}
        <div class="tab-pane fade" id="pills-{{related.book_id.split('-')[0]}}" role="tabpanel"
          aria-labelledby="pills-{{related.book_id.split('-')[0]}}-tab">
          <div class="card mb-3" style="max-width: 700px;">
            <div class="row g-0">
              <div class="col-md-4">
                <img src="{{book.img}}" alt="..." width="200px">
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <h5 class="card-title">{{book.name}}</h5>
                  {%if book.special_price !=0%}
                  <p><span class="h2 fs-2 fw-bold text-danger">{{book.special_price}}</span></p>
                  <p><span class="h2 text-decoration-line-through fs-4 ">{{book.current_price}}</span></p>
                  {%else%}
                  <span class="h2"><strong>{{book.current_price}}</strong>تومان</span>
                  {%endif%}

                </div>
              </div>
            </div>
            <div class="card-footer">
              <div class="row">
                <div class="col-md-4">
                  <p class="card-text"><small class="text-muted">{{book.updated_on}}</small></p>
                </div>
                <div class="col-md-6">
                  <a href="{{url_for('.ShowSubProduct', id=book.book_id)}}" class="btn btn-outline-primary">جزئیات</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
<script>
  // bar chart data
  var barData = {
    labels: [
      {% for item in labels %}
  "{{ item }}",
    {% endfor %}
    ],

  datasets: [{
    fillColor: "rgba(151,187,205,0.2)",
    strokeColor: "rgba(151,187,205,1)",
    pointColor: "rgba(151,187,205,1)",
    pointStrokeColor: "#fff",
    pointHighlightFill: "#fff",
    pointHighlightStroke: "rgba(151,187,205,1)",
    bezierCurve: false,
    data: [
      {% for item in values %}
          {{ item }},
  {% endfor %}]
      }
]
  }

  Chart.defaults.global.animationSteps = 50;
  Chart.defaults.global.tooltipYPadding = 16;
  Chart.defaults.global.tooltipCornerRadius = 0;
  Chart.defaults.global.tooltipTitleFontStyle = "normal";
  Chart.defaults.global.tooltipFillColor = "rgba(0,0,0,0.8)";
  Chart.defaults.global.animationEasing = "easeOutBounce";
  Chart.defaults.global.responsive = false;
  Chart.defaults.global.scaleLineColor = "black";
  Chart.defaults.global.scaleFontSize = 16;

  // get bar chart canvas
  var mychart = document.getElementById("chart").getContext("2d");

  steps = 10
  max = {{ max }}
  // draw bar chart
  var LineChartDemo = new Chart(mychart).Line(barData, {
    scaleOverride: true,
    scaleSteps: steps,
    scaleStepWidth: Math.ceil(max / steps),
    scaleStartValue: 0,
    scaleShowVerticalLines: true,
    scaleShowGridLines: true,
    barShowStroke: true,
    scaleShowLabels: true,
    bezierCurve: false,
  });

</script>
{% endblock %}

</html>

app/main/templates/subproduct.html
{% extends "layout.html" %}
{% set active_page = "subproduct" %}
{% block head %}
{{ super() }}
{% endblock %}
{% block content %}
<div class="container">
    <div class="row align-items-center">
        <div class="col-md-4" >
            <div class="shadow-lg p-5 m-3 bg-body rounded" style="max-height: 385px;">
                <img src="{{product.img}}" alt="" class="img-responsive push-bit border">
            </div>
        </div>
        <div class="col-md-8 align-middle">
            <div class="shadow-lg p-5 m-3 bg-body rounded">
                <div class="bg-light rounded p-3">
                    <p class="h1 text-right">{{product.name}}</p>
                </div>
                {%if product.special_price !=0%}
                    <label for="specialPrice">قیمت ویژه:</label>
                    <p><span class="h2 fs-2 fw-bold text-danger" id="specialPrice">{{product.special_price}}</span></p>
                    <label for="currentPrice">قیمت اصلی:</label>
                    <p><span class="h2 text-decoration-line-through fs-4" id="currentPrice">{{product.current_price}}</span></p>
                {%else%}
                    <label for="currentPrice">قیمت اصلی:</label>
                    <span class="h2 " id="currentPrice">{{product.current_price}}</span>
                {%endif%}
                <p>
                    
                </p>
            </div>
        </div>
    </div>
</div>
{%  endblock %}